/* =====================================================
   DATA — Movie & Show catalogue
   6 categories, each with 10 titles.
   ===================================================== */

const MOVIES = [
  {
    id: 1,
    title: "Dhurandhar",
    img: "movies img/dhurandhar.webp",
    banner: "banners/dhurandar.jpg",
    description: "An underworld saga following a network of criminals, informants and operatives whose lives intersect, navigating covert operations, espionage and betrayals.",
    year: 2025,
    rating: "A",
    duration: "3h 25m",
    genres: ["Thriller", "Crime", "Action"],
    type: "Movie",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
  },
  {
    id: 2,
    title: "Hello Baccho",
    img: "shows img/hello bachho.jpg",
    banner: "shows img/hello bachho.jpg",
    description: "A physics teacher sets out to make quality education accessible to all students through online learning,Based on the true story.",
    year: 2025,
    rating: "U/A 13+",
    duration: "5 Episodes",
    genres: ["Sincere", "Drama","Inspiring"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4"
  },
  {
    id: 3,
    title: "Kapil Sharma Show",
    img: "shows img/kapilshow.jpg",
    banner: "Images/trending image/kapil sharma show img.jpg",
    description: "India's favourite comedy show where Kapil Sharma hosts Bollywood stars and delivers laugh-out-loud performances every weekend.",
    year: 2024,
    rating: "U/A 13+",
    duration: "4 Seasons",
    genres: ["Comedy", "Talk Show","celebrities"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4"
  },
  {
    id: 4,
    title: "Tere Ishq Mein",
    img: "movies img/tere ishq mein.webp",
    banner: "movies img/tere ishq mein.webp",
    description: "Shankar and Mukti's intense love story unfolds against the backdrop of Benaras, exploring surrender and transformation that heals, hurts and changes them.",
    year: 2025,
    rating: "U/A 16+",
    duration: "2h 47m",
    genres: ["Romance", "Drama"],
    type: "Movie",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4"
  },
  {
    id: 5,
    title: "Stranger Things",
    img: "shows img/strangerthings.jpg",
    banner: "banners/ST.webp",
    description: "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl.",
    year: 2022,
    rating: "U/A 16+",
    duration: "5 Seasons",
    genres: ["Sci-Fi", "Horror", "Drama"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4"
  },
  {
    id: 6,
    title: "Wednesday",
    img: "shows img/wednesday.jpg",
    banner: "Images/trending image/Wednesday img.jpg",
    description: "Wednesday Addams is sent to Nevermore Academy, where she attempts to master her psychic ability and solve a mystery connected to her family.",
    year: 2022,
    rating: "U/A 13+",
    duration: "2 Season",
    genres: ["Comedy", "Mystery", "Fantasy"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4"
  },
  {
    id: 7,
    title: "Frankenstein",
    img: "movies img/frankenstein.jpg",
    banner: "movies img/frankenstein.jpg",
    description: "A modern retelling of Mary Shelley's classic where a brilliant scientist's creation threatens to destroy everything he holds dear.",
    year: 2024,
    rating: "U/A 16+",
    duration: "1h 52m",
    genres: ["Horror", "Sci-Fi", "Drama"],
    type: "Movie",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 8,
    title: "Mandala Murders",
    img: "shows img/mandala murders.jpg",
    banner: "Images/trending image/mandala murders img.webp",
    description: "Two investigators embark on a mission to uncover the enigma behind a series of murders, unveiling sinister secrets rooted in history.",
    year: 2024,
    rating: "A",
    duration: "1 Season",
    genres: ["Crime", "Mystery", "Thriller"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4"
  },
  {
    id: 9,
    title: "Raat Akeli Hai",
    img: "movies img/raat aleki hai.webp",
    banner: "Images/trending image/raat akeli hai img.webp",
    description: "A small-town cop investigates the murder of a wealthy patriarch on his wedding night, uncovering dark family secrets.",
    year: 2020,
    rating: "U/A 16+",
    duration: "2h 16m",
    genres: ["Mystery", "Crime", "Drama"],
    type: "Movie",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4"
  },
  {
    id: 10,
    title: "Bridgerton",
    img: "Shows img/brigeton.jpg",
    banner: "Images/trending image/bridgeton img.jpg",
    description: "Set in the glamorous Regency era, the Bridgerton family navigates London's high society in search of love, intrigue, and scandal.",
    year: 2023,
    rating: "U/A 16+",
    duration: "4 Seasons",
    genres: ["Romance", "Drama", "Period"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4"
  },
  {
    id: 201,
    title: "Anora",
    img: "movies img/anora.jpg",
    banner: "banners/anora.webp",
    description: "Anora, a young woman from Brooklyn, gets her chance at a Cinderella story when she meets and marries the son of an oligarch. Once the news reaches Russia, her fairytale is threatened as the parents set out for New York to get the marriage annulled.",
    year: 2020,
    rating: "A",
    duration: "2h 19m",
    genres: ["Offbeat", "romance", "Dark Comedy"],
    type: "Movie",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
  },
  {
    id: 202,
    title: "War Machine",
    img: "movies img/warmachine.jpg",
    banner: "Images/popular image/War Machine.jpg",
    description: "During the final stage of US Army Ranger selection, an elite team's training exercise turns into a fight for survival against an unimaginable threat.",
    year: 2026,
    rating: "U/A 16+",
    duration: "1h 49m",
    genres: ["Sci-Fi", "Violent", "Suspenseful"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
  },
  {
    id: 203,
    title: "Gladiator",
    img: "movies img/giladiator.jpg",
    banner: "movies img/giladiator.jpg",
    description: "Years after witnessing the death of Maximus at the hands of his uncle, Lucius must enter the Colosseum after the powerful emperors of Rome conquer his home. With rage in his heart and the future of the empire at stake, he looks to the past to find the strength and honor needed to return the glory of Rome to its people.",
    year: 2024,
    rating: "U/A 16+",
    duration: "2h 28m",
    genres: ["Epic", "Sword & Sandal", "Action"],
    type: "Movie",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
  },
  {
    id: 204,
    title: "One Piece",
    img: "shows img/one piece.avif",
    banner: "Images/popular image/One Piece.jpg",
    description: "Monkey D. Luffy and his pirate crew explore a fantastical world of endless oceans and exotic islands in search of the world's ultimate treasure to become the next Pirate King.",
    year: 2023,
    rating: "U/A 16+",
    duration: "2 Seasons",
    genres: ["Imaginative", "Adventure", "Rousing"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
  },
  {
    id: 205,
    title: "Taskaree: The Smuggler's Web",
    img: "shows img/taskaree.webp",
    banner: "Images/popular image/Taskaree.jpg",
    description: "A dedicated customs officer and his team take on a notorious smuggler leading a powerful syndicate, but unexpected obstacles threaten their mission.",
    year: 2026,
    rating: "U/A 16+",
    duration: "7 Episodes",
    genres: ["Crime", "Witty", "Thriller"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
  },
  {
    id: 206,
    title: "Chennai Express",
    img: "movies img/chennaiexp.webp",
    banner: "Images/popular image/Chennai Express.jpg",
    description: "Rahul, a young man, sets out to immerse his late grandfather's ashes at Rameshwaram. However, when he helps Meena, a runaway bride, board a train, he has to face the ire of her criminal family.",
    year: 2013,
    rating: "U/A 13+",
    duration: "2h 14m",
    genres: ["Exciting", "Emotional", "Adventure"],
    type: "Movie",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
  },
  {
    id: 207,
    title: "Chhaava",
    img: "movies img/chhava.webp",
    banner: "Images/popular image/Chhaava.jpg",
    description: "Shivaji's death sparks the Maratha-Mughal conflict. His son Sambhaji leads resistance against Aurangzeb's forces. Amid battles and intrigue, both sides face challenges in a struggle for power..",
    year: 2025,
    rating: "U/A 13+",
    duration: "2h 41m",
    genres: ["Action", "Epic", "History"],
    type: "Movie",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
  },
  {
    id: 11,
    title: "Dark",
    img: "shows img/dark2.jpg",
    banner: "banners/dark.webp",
    description: "When two children go missing in a small German town, its sinful past is exposed along with the double lives and fractured relationships that exist among four families as they search for the kids",
    year: 2017,
    rating: "U/A 16+",
    duration: "3 Seasons",
    genres: ["Sci-Fi", "Mystery", "Mind-Bending"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
  },
  {
    id: 12,
    title: "Money Heist",
    img: "shows img/money heist.jpg",
    banner: "banners/moneyhiest.webp",
    description: "A criminal mastermind who goes by 'The Professor' recruits eight people to carry out an elaborate heist on the Royal Mint of Spain.",
    year: 2021,
    rating: "U/A 16+",
    duration: "5 Seasons",
    genres: ["Suspenseful", "Exciting", "Thriller"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4"
  },
  {
    id: 13,
    title: "Red Notice",
    img: "movies img/red notice.jpg",
    banner: "Images/popular image/red-notice.jpg",
    description: "An FBI agent teams up with a notorious art thief to catch an even more notorious criminal in a globe-trotting adventure.",
    year: 2021,
    rating: "U/A 13+",
    duration: "1h 58m",
    genres: ["Action", "Comedy", "Thriller"],
    type: "Movie",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4"
  },
  {
    id: 14,
    title: "Dahmer",
    img: "shows img/dahmer.webp",
    banner: "Images/popular image/Dahmar img.webp",
    description: "The chilling true story of one of America's most notorious serial killers, as told through the eyes of his victims.",
    year: 2022,
    rating: "A",
    duration: "10 Episodes",
    genres: ["Crime", "Drama", "Biography"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4"
  },
  {
    id: 15,
    title: "Extraction",
    img: "movies img/extaction.jpg",
    banner: "banners/extraction.webp",
    description: "A hardened mercenary's mission becomes a soul-searching race to survive when he's sent to rescue a crime lord's kidnapped son.",
    year: 2020,
    rating: "U/A 16+",
    duration: "1h 58m",
    genres: ["Action", "Thriller"],
    type: "Movie",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4"
  },
  {
    id: 16,
    title: "Sacred Games",
    img: "shows img/sacredgames.jpg",
    banner: "Images/popular image/Sacred games img.webp",
    description: "A link in a chain of events leads a troubled cop to the doorstep of a powerful crime lord, uncovering a conspiracy that threatens Mumbai.",
    year: 2019,
    rating: "A",
    duration: "2 Seasons",
    genres: ["Crime", "Thriller", "Drama"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4"
  },
  {
    id: 17,
    title: "Adolescence",
    img: "shows img/adolescence.jpg",
    banner: "Images/popular image/adolescence img.jpg",
    description: "A coming-of-age drama exploring the lives of teenagers navigating love, identity, and the pressures of growing up in a connected world.",
    year: 2025,
    rating: "U/A 16+",
    duration: "4 Episodes",
    genres: ["Drama", "Coming-of-Age", "Crime"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 18,
    title: "13 Hours",
    img: "movies img/13hours.webp",
    banner: "Images/popular image/adolescence img.jpg",
    description: "A security team consisting of six members fights to defend an American diplomatic compound in Benghazi, Libya, against a wave of terrorist attacks.",
    year: 2025,
    rating: "A",
    duration: "2h 25m",
    genres: ["Explosive", "Action", "Thriller"],
    type: "Movie",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 19,
    title: "Fifty Shades of Grey",
    img: "movies img/50shades.webp",
    banner: "Images/popular image/adolescence img.jpg",
    description: "A coming-of-age drama exploring the lives of teenagers navigating love, identity, and the pressures of growing up in a connected world.",
    year: 2025,
    rating: "A",
    duration: "2h 5m",
    genres: ["Romance", "Exotic", "Steamy"],
    type: "Movie",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 20,
    title: "83",
    img: "movies img/83.webp",
    banner: "Images/popular image/adolescence img.jpg",
    description: "The incredible true story of the Indian cricket team's underdog victory at the 1983 World Cup.",
    year: 2021,
    rating: "U/A 13+",
    duration: "2h 42m",
    genres: ["Biography", "Drama", "Sports"],
    type: "Movie",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 21,
    title: "365 Days",
    img: "movies img/365.webp",
    banner: "Images/popular image/adolescence img.jpg",
    description: "A fiery executive in a spiritless relationship falls victim to a dominant mafia boss who imprisons her.",
    year: 2020,
    rating: "A",
    duration: "1h 54m",
    genres: ["Drama", "Romance"],
    type: "Movie",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 22,
    title: "Adam Project",
    img: "movies img/adam project.jpg",
    banner: "Images/popular image/adolescence img.jpg",
    description: "After accidentally crash-landing in 2022, time-traveling fighter pilot Adam Reed teams up with his 12-year-old self.",
    year: 2022,
    rating: "U/A 13+",
    duration: "1h 46m",
    genres: ["Action", "Adventure", "Sci-Fi"],
    type: "Movie",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 23,
    title: "Animal",
    img: "movies img/animal.webp",
    banner: "Images/popular image/adolescence img.jpg",
    description: "A son's obsessive love for his father leads to a brutal cycle of violence and vengeance.",
    year: 2023,
    rating: "A",
    duration: "3h 21m",
    genres: ["Action", "Crime", "Drama"],
    type: "Movie",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 24,
    title: "Atlas",
    img: "movies img/atlas.jpg",
    banner: "Images/popular image/adolescence img.jpg",
    description: "A brilliant data analyst with a deep distrust of AI joins a mission to capture a renegade robot.",
    year: 2024,
    rating: "U/A 13+",
    duration: "1h 58m",
    genres: ["Action", "Sci-Fi", "Thriller"],
    type: "Movie",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 25,
    title: "Baramulla",
    img: "movies img/baramulla.jpg",
    banner: "Images/popular image/adolescence img.jpg",
    description: "A gripping psychological thriller set against the volatile backdrop of the Baramulla district in Kashmir.",
    year: 2024,
    rating: "U/A 16+",
    duration: "2h 10m",
    genres: ["Thriller", "Mystery"],
    type: "Movie",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 26,
    title: "Bhool Bhulaiyaa 3",
    img: "movies img/BB3.webp",
    banner: "Images/popular image/adolescence img.jpg",
    description: "Rooh Baba returns to face a terrifying spirit in a haunted mansion, blending laughs with chills.",
    year: 2024,
    rating: "U/A 13+",
    duration: "2h 38m",
    genres: ["Comedy", "Horror"],
    type: "Movie",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 30,
    title: "Damsel",
    img: "movies img/damsel.jpg",
    banner: "Images/popular image/adolescence img.jpg",
    description: "A dutiful damsel agrees to marry a handsome prince, only to find the royal family has recruited her as a sacrifice to repay an ancient debt.",
    year: 2024,
    rating: "U/A 13+",
    duration: "1h 48m",
    genres: ["Fantasy", "Action", "Adventure"],
    type: "Movie",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 31,
    title: "Dangal",
    img: "movies img/dangal.webp",
    banner: "Images/popular image/adolescence img.jpg",
    description: "Former wrestler Mahavir Singh Phogat and his two wrestler daughters struggle towards glory at the Commonwealth Games.",
    year: 2016,
    rating: "U",
    duration: "2h 41m",
    genres: ["Biography", "Action", "Drama"],
    type: "Movie",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 32,
    title: "De De Pyaar De 2",
    img: "movies img/dedepyaarde2.webp",
    banner: "Images/popular image/adolescence img.jpg",
    description: "Ashish and Ayesha's relationship faces a new set of hilarious and emotional challenges with their families.",
    year: 2025,
    rating: "U/A 13+",
    duration: "2h 20m",
    genres: ["Comedy", "Romance"],
    type: "Movie",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 33,
    title: "Don't Look Up",
    img: "movies img/dont look up.jpg",
    banner: "Images/popular image/adolescence img.jpg",
    description: "Two low-level astronomers must go on a giant media tour to warn mankind of an approaching comet that will destroy Earth.",
    year: 2021,
    rating: "A",
    duration: "2h 18m",
    genres: ["Comedy", "Sci-Fi", "Drama"],
    type: "Movie",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 34,
    title: "Dragon",
    img: "movies img/dragon.webp",
    banner: "Images/popular image/adolescence img.jpg",
    description: "A supernatural action thriller following a man who discovers he possesses the ancient power of the dragon.",
    year: 2025,
    rating: "U/A 16+",
    duration: "2h 15m",
    genres: ["Action", "Fantasy"],
    type: "Movie",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 35,
    title: "Eko",
    img: "movies img/eko.webp",
    banner: "Images/popular image/adolescence img.jpg",
    description: "A high-concept sci-fi thriller exploring the consequences of human-tech integration in a near-future society.",
    year: 2025,
    rating: "U/A 13+",
    duration: "2h 05m",
    genres: ["Sci-Fi", "Thriller"],
    type: "Movie",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 36,
    title: "Jewel Thief",
    img: "movies img/ewel theif.jpg",
    banner: "Images/popular image/adolescence img.jpg",
    description: "An urban heist thriller where a master of disguise targets the elite, leading to a high-stakes cat-and-mouse game.",
    year: 2025,
    rating: "U/A 16+",
    duration: "2h 12m",
    genres: ["Crime", "Thriller", "Action"],
    type: "Movie",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 37,
    title: "Extraction",
    img: "movies img/extraction.jpg",
    banner: "banners/extraction.jpg",
    description: "A former special forces operative must save the kidnapped son of an international crime lord.",
    year: 2025,
    rating: "U/A 16+",
    duration: "1h 56m",
    genres: ["Action", "Crime", "Drama"],
    type: "Movie",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
{
    id: 38,
    title: "Frankenstein",
    img: "movies img/frankenstein.jpg",
    banner: "Images/popular image/adolescence img.jpg",
    description: "A modern reimagining of Mary Shelley's classic tale about a scientist who brings a creature to life.",
    year: 2025,
    rating: "A",
    duration: "2h 10m",
    genres: ["Horror", "Sci-Fi", "Drama"],
    type: "Movie",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 39,
    title: "Gangubai Kathiawadi",
    img: "movies img/gangubai.webp",
    banner: "Images/popular image/adolescence img.jpg",
    description: "Dupe into a life of prostitution, Gangubai becomes a powerful figure in the underworld and a champion for women's rights.",
    year: 2022,
    rating: "U/A 16+",
    duration: "2h 32m",
    genres: ["Biography", "Crime", "Drama"],
    type: "Movie",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 40,
    title: "The Gray Man",
    img: "movies img/greyman.jpg",
    banner: "Images/popular image/adolescence img.jpg",
    description: "When the CIA's most skilled operative reveals dark agency secrets, he becomes a target of international assassins.",
    year: 2022,
    rating: "U/A 13+",
    duration: "2h 02m",
    genres: ["Action", "Thriller"],
    type: "Movie",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 41,
    title: "HAQ",
    img: "movies img/HAQ.webp",
    banner: "Images/popular image/adolescence img.jpg",
    description: "A gritty legal drama centered on a lawyer's fight for justice against a corrupt systemic power.",
    year: 2024,
    rating: "U/A 16+",
    duration: "2h 18m",
    genres: ["Drama", "Crime"],
    type: "Movie",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 42,
    title: "Heart of Stone",
    img: "movies img/heart of stone.jpg",
    banner: "Images/popular image/adolescence img.jpg",
    description: "An intelligence operative for a shadowy global peacekeeping agency races to stop a hacker from stealing its most dangerous weapon.",
    year: 2023,
    rating: "U/A 13+",
    duration: "2h 02m",
    genres: ["Action", "Thriller", "Crime"],
    type: "Movie",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 43,
    title: "Idli Kadai",
    img: "movies img/idli kadai.webp",
    banner: "Images/popular image/adolescence img.jpg",
    description: "A heartwarming slice-of-life story following the daily struggles and joys of a small-town eatery owner.",
    year: 2025,
    rating: "U",
    duration: "2h 10m",
    genres: ["Drama", "Comedy"],
    type: "Movie",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 44,
    title: "Interceptor",
    img: "movies img/interceptor.jpg",
    banner: "Images/popular image/adolescence img.jpg",
    description: "An Army captain uses her years of tactical training to save humanity when a coordinated attack threatens a remote missile interceptor station.",
    year: 2022,
    rating: "A",
    duration: "1h 39m",
    genres: ["Action", "Adventure", "Thriller"],
    type: "Movie",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 45,
    title: "Kalki 2898 AD",
    img: "movies img/kalki.webp",
    banner: "Images/popular image/adolescence img.jpg",
    description: "In a post-apocalyptic world, a modern-day avatar of Vishnu descends to Earth to protect the world from evil forces.",
    year: 2024,
    rating: "U/A 13+",
    duration: "3h 01m",
    genres: ["Sci-Fi", "Action", "Drama"],
    type: "Movie",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 46,
    title: "Karate Kid Legend",
    img: "movies img/karatekid.webp",
    banner: "Images/popular image/adolescence img.jpg",
    description: "A new student from the US moves to Beijing and learns to defend himself through the teachings of a wise mentor.",
    year: 2025,
    rating: "U/A 13+",
    duration: "2h 10m",
    genres: ["Action", "Drama", "Family"],
    type: "Movie",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 47,
    title: "Kathal",
    img: "movies img/kathel.jpg",
    banner: "Images/popular image/adolescence img.jpg",
    description: "When two prized jackfruits disappear from a politician's garden, a spirited police officer finds herself solving a bizarre case.",
    year: 2023,
    rating: "U/A 13+",
    duration: "1h 55m",
    genres: ["Comedy", "Crime", "Mystery"],
    type: "Movie",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 48,
    title: "Laapata Ladies",
    img: "movies img/laapata ladies.webp",
    banner: "Images/popular image/adolescence img.jpg",
    description: "The misadventures of two young brides who get lost from the same train, leading to a series of funny and moving discoveries.",
    year: 2024,
    rating: "U/A 13+",
    duration: "2h 02m",
    genres: ["Comedy", "Drama"],
    type: "Movie",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 49,
    title: "Jolly LLB 3",
    img: "movies img/llb3.webp",
    banner: "Images/popular image/adolescence img.jpg",
    description: "The two Jollys face off in a court of law, tackling a massive case while navigating a world of corruption and humor.",
    year: 2025,
    rating: "U/A 13+",
    duration: "2h 25m",
    genres: ["Comedy", "Drama", "Crime"],
    type: "Movie",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 50,
    title: "Lucky Baskar",
    img: "movies img/lucky baskar.webp",
    banner: "Images/popular image/adolescence img.jpg",
    description: "A simple bank cashier's life takes a dramatic turn when he enters the high-stakes world of financial fraud.",
    year: 2024,
    rating: "U/A 13+",
    duration: "2h 30m",
    genres: ["Drama", "Crime", "Thriller"],
    type: "Movie",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 51,
    title: "Maharaja",
    img: "movies img/maharaja.webp",
    banner: "Images/popular image/adolescence img.jpg",
    description: "A barber seeks vengeance after his home is burgled, telling police his 'Lakshmi' has been stolen, leading to a twisted mystery.",
    year: 2024,
    rating: "U/A 16+",
    duration: "2h 22m",
    genres: ["Action", "Crime", "Drama"],
    type: "Movie",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 52,
    title: "Maareesan",
    img: "movies img/mareesan.webp",
    banner: "Images/popular image/adolescence img.jpg",
    description: "A period action-drama exploring the life of a warrior fighting against social injustice and oppression.",
    year: 2025,
    rating: "U/A 16+",
    duration: "2h 35m",
    genres: ["Action", "Drama"],
    type: "Movie",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 53,
    title: "Mission Majnu",
    img: "movies img/mission majnu.jpg",
    banner: "Images/popular image/adolescence img.jpg",
    description: "In the 1970s, an Indian spy undertakes a deadly mission to expose a covert nuclear weapons program in Pakistan.",
    year: 2023,
    rating: "U/A 16+",
    duration: "2h 09m",
    genres: ["Action", "Drama", "History"],
    type: "Movie",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 54,
    title: "Mahaavtaar Narsimha",
    img: "movies img/narsimha.webp",
    banner: "Images/popular image/adolescence img.jpg",
    description: "An animated epic depicting the story of Lord Vishnu's fourth incarnation as Narsimha to defeat the demon king Hiranyakashipu.",
    year: 2024,
    rating: "U",
    duration: "1h 45m",
    genres: ["Animation", "Action", "Fantasy"],
    type: "Movie",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 55,
    title: "Nowhere",
    img: "movies img/nowhere.jpg",
    banner: "Images/popular image/adolescence img.jpg",
    description: "A pregnant woman trapped in a shipping container adrift in the sea must struggle to survive after fleeing a totalitarian country.",
    year: 2023,
    rating: "A",
    duration: "1h 49m",
    genres: ["Drama", "Thriller"],
    type: "Movie",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 56,
    title: "Oldgaurd",
    img: "movies img/oldgard.jpg",
    banner: "Images/popular image/adolescence img.jpg",
    description: "A group of immortal mercenaries are suddenly exposed and must fight to keep their identity a secret.",
    year: 2020,
    rating: "A",
    duration: "2h 05m",
    genres: ["Action", "Fantasy"],
    type: "Movie",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 57,
    title: "Om Shanti Om",
    img: "movies img/omshantiom.webp",
    banner: "Images/popular image/adolescence img.jpg",
    description: "A struggling actor is reincarnated to seek justice for the murder of the woman he loved in his past life.",
    year: 2007,
    rating: "U/A",
    duration: "2h 42m",
    genres: ["Drama", "Musical", "Romance"],
    type: "Movie",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 58,
    title: "Peaky Blinders: The Immortal man",
    img: "movies img/peakyblinders.jpg",
    banner: "Images/popular image/adolescence img.jpg",
    description: "A feature film conclusion to the epic saga of Thomas Shelby and his family as they navigate the aftermath of the war.",
    year: 2025,
    rating: "A",
    duration: "2h 15m",
    genres: ["Crime", "Drama"],
    type: "Movie",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 59,
    title: "PK",
    img: "movies img/pk.webp",
    banner: "Images/popular image/adolescence img.jpg",
    description: "An alien on Earth loses his communication device and questions social dogmas through his innocent perspective.",
    year: 2014,
    rating: "U/A",
    duration: "2h 33m",
    genres: ["Comedy", "Sci-Fi", "Drama"],
    type: "Movie",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 60,
    title: "Pushpa: The Rule",
    img: "movies img/pushpa2.webp",
    banner: "Images/popular image/adolescence img.jpg",
    description: "Pushpa Raj dominates the red sandalwood smuggling world, facing new enemies and internal conflicts in this epic sequel.",
    year: 2024,
    rating: "U/A 16+",
    duration: "3h 20m",
    genres: ["Action", "Crime", "Drama"],
    type: "Movie",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 62,
    title: "Rab Ne Bana Di Jodi",
    img: "movies img/rab ne bana di jodi.webp",
    banner: "Images/popular image/adolescence img.jpg",
    description: "A mild-mannered man creates a loud alter-ego to win the love of his vivacious wife in a dance competition.",
    year: 2008,
    rating: "U",
    duration: "2h 47m",
    genres: ["Comedy", "Drama", "Romance"],
    type: "Movie",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 63,
    title: "Red Notice",
    img: "movies img/rednotice.jpg",
    banner: "Images/popular image/adolescence img.jpg",
    description: "An FBI profiler chasing the world's most wanted art thief becomes her reluctant partner in crime to catch an elusive crook.",
    year: 2021,
    rating: "U/A 13+",
    duration: "1h 58m",
    genres: ["Action", "Comedy", "Crime"],
    type: "Movie",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 64,
    title: "The RIP",
    img: "movies img/RIP.jpg",
    banner: "Images/popular image/adolescence img.jpg",
    description: "A supernatural thriller where agents of the afterlife must prevent a catastrophic breach between worlds.",
    year: 2025,
    rating: "U/A 16+",
    duration: "2h 05m",
    genres: ["Action", "Fantasy", "Sci-Fi"],
    type: "Movie",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 65,
    title: "RRR",
    img: "movies img/RRR.webp",
    banner: "Images/popular image/adolescence img.jpg",
    description: "A fictional story about two legendary revolutionaries and their journey away from home before they started fighting for their country in the 1920s.",
    year: 2022,
    rating: "U/A 16+",
    duration: "3h 07m",
    genres: ["Action", "Drama"],
    type: "Movie",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 66,
    title: "Saiyaara",
    img: "movies img/Saiyaara.webp",
    banner: "Images/popular image/adolescence img.jpg",
    description: "A romantic drama that spans across borders, following two souls connected by fate and a shared love for music.",
    year: 2025,
    rating: "U/A 13+",
    duration: "2h 15m",
    genres: ["Romance", "Drama", "Musical"],
    type: "Movie",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 67,
    title: "Sikandar ka mukaddar",
    img: "movies img/sikander ka mukaddar.jpg",
    banner: "Images/popular image/adolescence img.jpg",
    description: "A hard-hitting heist thriller centered around a diamond robbery and a relentless pursuit by a determined cop.",
    year: 2024,
    rating: "U/A 16+",
    duration: "2h 10m",
    genres: ["Crime", "Thriller", "Drama"],
    type: "Movie",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 68,
    title: "Sunny Sanskari Ki Tulsi Kumari",
    img: "movies img/Sunny sanskari.webp",
    banner: "Images/popular image/adolescence img.jpg",
    description: "A vibrant romantic comedy following the cultural clashes and romantic sparks between Sunny and Tulsi.",
    year: 2025,
    rating: "U/A 13+",
    duration: "2h 20m",
    genres: ["Comedy", "Romance", "Drama"],
    type: "Movie",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 69,
    title: "Uncharted",
    img: "movies img/uncharted.webp",
    banner: "Images/popular image/adolescence img.jpg",
    description: "Street-smart Nathan Drake is recruited by seasoned treasure hunter Victor 'Sully' Sullivan to recover a fortune lost 500 years ago.",
    year: 2022,
    rating: "U/A 13+",
    duration: "1h 56m",
    genres: ["Action", "Adventure"],
    type: "Movie",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 70,
    title: "war 2",
    img: "movies img/war2.webp",
    banner: "Images/popular image/adolescence img.jpg",
    description: "Things get complicated when Kabir Dhaliwal, a secret agent, is accused of betraying his nation and his former batchmate shoulders the responsibility of finding him.",
    year: 2025,
    rating: "U/A 16+",
    duration: "2h 53m",
    genres: ["Explosive", "Action", "Thriller"],
    type: "Movie",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 71,
    title: "3 Body Problem",
    img: "shows img/3 bodu problem.jpg",
    banner: "Images/popular image/adolescence img.jpg",
    description: "Across continents and decades, five brilliant friends make earth-shattering discoveries as the laws of science unravel and an existential threat emerges.",
    year: 2024,
    rating: "A",
    duration: "8 Episodes",
    genres: ["Sci-Fi", "Mystery", "Adventure"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 72,
    title: "Alice in borderland",
    img: "shows img/alice in borderland.jpg",
    banner: "Images/popular image/adolescence img.jpg",
    description: "An obsessed gamer and his friends find themselves in a deserted Tokyo where they must compete in dangerous games to survive.",
    year: 2020,
    rating: "A",
    duration: "2 Seasons",
    genres: ["Sci-Fi", "Thriller", "Action"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 73,
    title: "All of Us Are Dead",
    img: "shows img/allofusaredead.jpg",
    banner: "Images/popular image/adolescence img.jpg",
    description: "A high school becomes ground zero for a zombie virus outbreak. Trapped students must fight their way out or turn into one of the rabid infected.",
    year: 2022,
    rating: "A",
    duration: "12 Episodes",
    genres: ["Horror", "Action", "Drama"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 74,
    title: "Avtar: The Last Airbender",
    img: "shows img/avtar.jpg",
    banner: "Images/popular image/adolescence img.jpg",
    description: "A young boy known as the Avatar must master the four elemental powers to save a world at war and fight a ruthless enemy.",
    year: 2024,
    rating: "U/A 13+",
    duration: "8 Episodes",
    genres: ["Fantasy", "Adventure", "Action"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 75,
    title: "Bads of Bollywood",
    img: "shows img/badsofbollywood.jpg",
    banner: "Images/popular image/adolescence img.jpg",
    description: "A deep dive into the evolution of the 'villain' in Indian cinema, exploring the iconic actors who defined evil on screen.",
    year: 2024,
    rating: "U/A 13+",
    duration: "1 Season",
    genres: ["Comedy", "Chilling","Bollywood"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 76,
    title: "Bakitu",
    img: "shows img/bakitu.jpg",
    banner: "Images/popular image/adolescence img.jpg",
    description: "Five years after the Great Raitai Tournament, Baki Hanma trains intensely to challenge his father, Yuujirou Hanma.",
    year: 2023,
    rating: "A",
    duration: "2 Seasons",
    genres: ["Anime", "Action", "Martial Arts"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 77,
    title: "Better Call Saul",
    img: "shows img/bettercallsaul.webp",
    banner: "Images/popular image/adolescence img.jpg",
    description: "The trials and tribulations of criminal lawyer Jimmy McGill in the years leading up to his fateful run-in with Walter White.",
    year: 2015,
    rating: "A",
    duration: "6 Seasons",
    genres: ["Crime", "Drama"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 78,
    title: "Bodyguard",
    img: "shows img/bodyguard.jpg",
    banner: "Images/popular image/adolescence img.jpg",
    description: "A war veteran is assigned to protect a politician whose politics he despises, leading to a web of conspiracy and danger.",
    year: 2018,
    rating: "A",
    duration: "6 Episodes",
    genres: ["Thriller", "Crime", "Drama"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 79,
    title: "Breaking Bad",
    img: "shows img/breaking bad.webp",
    banner: "Images/popular image/adolescence img.jpg",
    description: "A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine.",
    year: 2008,
    rating: "A",
    duration: "5 Seasons",
    genres: ["Crime", "Drama", "Thriller"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 80,
    title: "Chainsaw Man",
    img: "shows img/chainsaw man.webp",
    banner: "Images/popular image/adolescence img.jpg",
    description: "Denji, a teenager living in poverty, is reborn as a powerful Devil Hunter with chainsaw limbs after merging with his pet devil.",
    year: 2022,
    rating: "A",
    duration: "12 Episodes",
    genres: ["Anime", "Action", "Horror"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 81,
    title: "Cobra Kai",
    img: "shows img/cobra kai.jpg",
    banner: "Images/popular image/adolescence img.jpg",
    description: "Decades after their 1984 All Valley Karate Tournament bout, a middle-aged Daniel LaRusso and Johnny Lawrence find themselves martial-arts rivals again.",
    year: 2018,
    rating: "U/A 16+",
    duration: "6 Seasons",
    genres: ["Action", "Comedy", "Drama"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 82,
    title: "Death Note",
    img: "shows img/deathnote.webp",
    banner: "Images/popular image/adolescence img.jpg",
    description: "An intelligent high school student goes on a secret crusade to eliminate criminals from the world after discovering a notebook that can kill anyone.",
    year: 2006,
    rating: "U/A 16+",
    duration: "37 Episodes",
    genres: ["Anime", "Mystery", "Thriller"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 83,
    title: "Delhi Crime",
    img: "shows img/delhicrime.jpg",
    banner: "Images/popular image/adolescence img.jpg",
    description: "Based on real-life case files, this anthology series follows the Delhi Police as they investigate high-profile crimes.",
    year: 2019,
    rating: "A",
    duration: "3 Seasons",
    genres: ["Crime", "Drama"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 84,
    title: "Demon Slayer",
    img: "shows img/demon slayer.webp",
    banner: "Images/popular image/adolescence img.jpg",
    description: "A family is attacked by demons and only two members survive - Tanjiro and his sister Nezuko, who is turning into a demon slowly.",
    year: 2019,
    rating: "U/A 16+",
    duration: "4 Seasons",
    genres: ["Anime", "Action", "Fantasy"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 85,
    title: "Dragon Ball Z",
    img: "shows img/dragonball Z.webp",
    banner: "Images/popular image/adolescence img.jpg",
    description: "Goku and his companions defend the Earth against an assortment of villains ranging from intergalactic space fighters to powerful androids.",
    year: 1989,
    rating: "U/A 13+",
    duration: "9 Seasons",
    genres: ["Anime", "Action", "Adventure"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 86,
    title: "Elite",
    img: "shows img/elite.jpg",
    banner: "Images/popular image/adolescence img.jpg",
    description: "When three working-class teenagers begin attending an exclusive private school in Spain, the clash between them and the wealthy students leads to murder.",
    year: 2018,
    rating: "A",
    duration: "8 Seasons",
    genres: ["Crime", "Drama", "Thriller"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 87,
    title: "Emily in Paris",
    img: "shows img/emily in paris.jpg",
    banner: "Images/popular image/adolescence img.jpg",
    description: "A young American woman from the Midwest is hired by a marketing firm in Paris to provide them with an American perspective on things.",
    year: 2020,
    rating: "U/A 16+",
    duration: "4 Seasons",
    genres: ["Comedy", "Romance", "Drama"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 88,
    title: "Good Doctor",
    img: "shows img/good doctor.webp",
    banner: "Images/popular image/adolescence img.jpg",
    description: "Shaun Murphy, a young surgeon with autism and Savant syndrome, is recruited into the surgical unit of a prestigious hospital.",
    year: 2017,
    rating: "U/A 16+",
    duration: "7 Seasons",
    genres: ["Drama"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 89,
    title: "Heeramandi",
    img: "shows img/heeramandi.jpg",
    banner: "Images/popular image/adolescence img.jpg",
    description: "In pre-independent India, the lives of courtesans in the red-light district of Heera Mandi are filled with love, betrayal, and politics.",
    year: 2024,
    rating: "U/A 16+",
    duration: "8 Episodes",
    genres: ["Drama", "History", "Romance"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 90,
    title: "Hellbound",
    img: "shows img/hellbound.jpg",
    banner: "show img/hellbound.webp",
    description: "Unearthly beings deliver bloody condemnations, sending individuals to hell and giving rise to a religious group founded on the idea of divine justice.",
    year: 2021,
    rating: "A",
    duration: "2 Seasons",
    genres: ["Horror", "Mystery", "Crime"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 91,
    title: "House of cards",
    img: "shows img/house of cards.jpg",
    banner: "shows img/house of cards.jpg",
    description: "A Congressman works with his equally conniving wife to exact revenge on the people who betrayed him.",
    year: 2013,
    rating: "A",
    duration: "6 Seasons",
    genres: ["Drama"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 92,
    title: "Jamtara",
    img: "shows img/jamtara.jpg",
    banner: "Images/popular image/adolescence img.jpg",
    description: "A group of small-town young men run a lucrative phishing operation until a corrupt politician wants in on their scheme.",
    year: 2020,
    rating: "A",
    duration: "2 Seasons",
    genres: ["Crime", "Drama"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 93,
    title: "Jijutsu Kaisen",
    img: "shows img/jijutsu.webp",
    banner: "Images/popular image/adolescence img.jpg",
    description: "A boy swallows a cursed talisman and becomes cursed himself. He enters a shaman's school to be able to locate the demon's other body parts and thus exorcise himself.",
    year: 2020,
    rating: "A",
    duration: "2 Seasons",
    genres: ["Anime", "Action", "Fantasy"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 94,
    title: "Kota Factory",
    img: "shows img/kota factory.jpg",
    banner: "Images/popular image/adolescence img.jpg",
    description: "Dedicated to the students of Kota, the show captures the life of IIT-JEE aspirants and their struggle to clear the entrance exams.",
    year: 2019,
    rating: "U/A 16+",
    duration: "3 Seasons",
    genres: ["Comedy", "Drama"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 95,
    title: "Kurukshetra",
    img: "shows img/Kurukshetra.jpg",
    banner: "Images/popular image/adolescence img.jpg",
    description: "A modern retelling of the epic battle of Mahabharata, exploring the themes of duty, family, and power.",
    year: 2024,
    rating: "U/A 13+",
    duration: "10 Episodes",
    genres: ["Drama", "Action", "Mythology"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 96,
    title: "Locke & Key",
    img: "shows img/locke and key.jpg",
    banner: "shows img/locke & key.webp",
    description: "After their father is murdered, three siblings move into a house filled with reality-bending keys.",
    year: 2020,
    rating: "U/A 13+",
    duration: "3 Seasons",
    genres: ["Fantasy", "Horror", "Mystery"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 97,
    title: "Lucifer",
    img: "shows img/lucifer.jpg",
    banner: "shows img/lucifer.webp",
    description: "Lucifer Morningstar has decided he's had enough of being the dutiful servant in Hell and decides to spend some time on Earth to better understand humanity.",
    year: 2016,
    rating: "A",
    duration: "6 Seasons",
    genres: ["Crime", "Fantasy", "Drama"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 98,
    title: "Mandala Murders",
    img: "shows img/Mandala murders.jpg",
    banner: "Images/popular image/adolescence img.jpg",
    description: "Detectives race against time to solve a series of grisly murders linked by a mysterious religious symbol.",
    year: 2024,
    rating: "A",
    duration: "8 Episodes",
    genres: ["Crime", "Thriller", "Mystery"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 99,
    title: "Money Heist",
    img: "shows img/money heist.jpg",
    banner: "shows img/money heist.jpg",
    description: "An unusual group of robbers attempt to carry out the most perfect robbery in Spanish history - stealing 2.4 billion Euros from the Royal Mint of Spain.",
    year: 2017,
    rating: "A",
    duration: "5 Seasons",
    genres: ["Action", "Crime", "Drama"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 100,
    title: "My Hero Academia",
    img: "shows img/my hero academy.webp",
    banner: "shows img/my hero academia.webp",
    description: "A superhero-loving boy without any powers is determined to enroll in a prestigious hero academy and learn what it really means to be a hero.",
    year: 2016,
    rating: "U/A 13+",
    duration: "7 Seasons",
    genres: ["Anime", "Action", "Adventure"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 101,
    title: "Narcos",
    img: "shows img/narcos.jpg",
    banner: "shows img/narcos.webp",
    description: "A chronicled look at the criminal exploits of Colombian drug lord Pablo Escobar, as well as many other drug kingpins who plagued the country through the years.",
    year: 2015,
    rating: "A",
    duration: "3 Seasons",
    genres: ["Biography", "Crime", "Drama"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 102,
    title: "One Punch Man",
    img: "shows img/one punch man.webp",
    banner: "shows img/one punch man.webp",
    description: "The story of Saitama, a hero who can defeat any enemy with a single punch, but suffers from boredom due to his overwhelming strength.",
    year: 2015,
    rating: "U/A 16+",
    duration: "2 Seasons",
    genres: ["Anime", "Action", "Comedy"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 103,
    title: "One piece",
    img: "shows img/one-piece anime.webp",
    banner: "Images/popular image/adolescence img.jpg",
    description: "Monkey D. Luffy and his pirate crew explore a fantastical world of endless oceans and exotic islands in search of the world's ultimate treasure.",
    year: 1999,
    rating: "U/A 13+",
    duration: "21 Seasons",
    genres: ["Anime", "Action", "Adventure"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 104,
    title: "Ozark",
    img: "shows img/ozark.jpg",
    banner: "shows img/ozark.webp",
    description: "A financial advisor drags his family from Chicago to the Missouri Ozarks, where he must launder money to appease a drug boss.",
    year: 2017,
    rating: "A",
    duration: "4 Seasons",
    genres: ["Crime", "Drama", "Thriller"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 105,
    title: "Parayte",
    img: "shows img/Parasyte.webp",
    banner: "shows img/Parayte.webp",
    description: "A teenager's hand is taken over by a parasite, and they must work together to survive and stop others of its kind from consuming humanity.",
    year: 2014,
    rating: "A",
    duration: "24 Episodes",
    genres: ["Anime", "Action", "Sci-Fi"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 106,
    title: "Peaky Blinder",
    img: "shows img/Peaky Blinders.jpg",
    banner: "shows img/Peaky Blinder.webp",
    description: "A gangster family epic set in 1900s England, centering on a gang who sew razor blades in the peaks of their caps.",
    year: 2013,
    rating: "A",
    duration: "6 Seasons",
    genres: ["Crime", "Drama"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 107,
    title: "Queens Gambit",
    img: "shows img/queensgambit.jpg",
    banner: "shows img/Queens Gambit.webp",
    description: "Orphaned at nine, prodigious introvert Beth Harmon discovers and masters the game of chess in 1960s USA.",
    year: 2020,
    rating: "U/A 16+",
    duration: "7 Episodes",
    genres: ["Drama"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 108,
    title: "Rana Naidu",
    img: "shows img/Raina Naidu.jpg",
    banner: "Images/popular image/adolescence img.jpg",
    description: "Rana Naidu is the go-to fixer for Bollywood's elite, but his life is thrown into chaos when his father is released from prison.",
    year: 2023,
    rating: "A",
    duration: "1 Season",
    genres: ["Action", "Crime", "Drama"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 109,
    title: "Sakamoto Days",
    img: "shows img/sakamoto.jpg",
    banner: "shows img/sakamoto days.webp",
    description: "Taro Sakamoto, an unbeatable legendary assassin, retires and settles down to run a neighborhood grocery store, but his past soon catches up.",
    year: 2025,
    rating: "A",
    duration: "12 Episodes",
    genres: ["Anime", "Action", "Comedy"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 110,
    title: "Sandman",
    img: "shows img/sandman.jpg",
    banner: "shows img/sandman.webp",
    description: "Upon escaping after decades of imprisonment by a mortal wizard, Dream, the personification of dreams, sets out to reclaim his lost equipment.",
    year: 2022,
    rating: "A",
    duration: "1 Season",
    genres: ["Fantasy", "Drama", "Mystery"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 111,
    title: "Sex Education",
    img: "shows img/sexeducation.jpg",
    banner: "shows img/sex education.webp",
    description: "A teenage boy with a sex therapist mother teams up with a high school classmate to set up an underground sex therapy clinic at school.",
    year: 2019,
    rating: "A",
    duration: "4 Seasons",
    genres: ["Comedy", "Drama"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 112,
    title: "Shadow and Bone",
    img: "shows img/shadow and bones.jpg",
    banner: "Images/popular image/adolescence img.jpg",
    description: "Sinister forces plot against a young soldier when she reveals a magical power that might unite her world.",
    year: 2021,
    rating: "U/A 16+",
    duration: "2 Seasons",
    genres: ["Fantasy", "Action", "Drama"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 113,
    title: "Squid Game",
    img: "shows img/squid games.jpg",
    banner: "shows img/squid game.webp",
    description: "Hundreds of cash-strapped players accept a strange invitation to compete in children's games. Inside, a tempting prize awaits with deadly high stakes.",
    year: 2021,
    rating: "A",
    duration: "2 Seasons",
    genres: ["Thriller", "Action", "Drama"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 114,
    title: "Suits",
    img: "shows img/suits.webp",
    banner: "shows img/suits.webp",
    description: "On the run from a drug deal gone bad, brilliant college dropout Mike Ross finds himself working with Harvey Specter, one of NYC's best lawyers.",
    year: 2011,
    rating: "U/A 16+",
    duration: "9 Seasons",
    genres: ["Comedy", "Drama"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 115,
    title: "The Witcher",
    img: "shows img/thewitcher.jpg",
    banner: "shows img/the witcher.webp",
    description: "Geralt of Rivia, a solitary monster hunter, struggles to find his place in a world where people often prove more wicked than beasts.",
    year: 2019,
    rating: "A",
    duration: "3 Seasons",
    genres: ["Fantasy", "Action", "Adventure"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 116,
    title: "Titans",
    img: "shows img/titans.jpg",
    banner: "shows img/Titans.webp",
    description: "A team of young superheroes led by Nightwing combat evil and other perils in this gritty take on the DC franchise.",
    year: 2018,
    rating: "A",
    duration: "4 Seasons",
    genres: ["Action", "Adventure", "Crime"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 117,
    title: "Umbrella Academy",
    img: "shows img/umbrella academy.jpg",
    banner: "shows img/umbrella academy.webp",
    description: "A family of former child heroes, now grown apart, must reunite to continue to protect the world.",
    year: 2019,
    rating: "U/A 16+",
    duration: "4 Seasons",
    genres: ["Action", "Adventure", "Comedy"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 118,
    title: "Vampire Diaries",
    img: "shows img/vampiredairy.webp",
    banner: "shows img/vampire diaries.webp",
    description: "The lives, loves, dangers and disasters in the town, Mystic Falls, Virginia. Creatures of unspeakable horror lurk beneath this town as a teenage girl is suddenly torn between two vampire brothers.",
    year: 2009,
    rating: "U/A 16+",
    duration: "8 Seasons",
    genres: ["Drama", "Fantasy", "Horror"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 119,
    title: "Vikings",
    img: "shows img/vikings.webp",
    banner: "shows img/Vikings.webp",
    description: "Vikings transports us to the brutal and mysterious world of Ragnar Lothbrok, a Viking warrior and farmer who yearns to explore—and raid—the distant shores across the ocean.",
    year: 2013,
    rating: "A",
    duration: "6 Seasons",
    genres: ["Action", "Adventure", "Drama"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 120,
    title: "Walking Dead",
    img: "shows img/walkingdead.webp",
    banner: "shows img/Walking Dead.webp",
    description: "Sheriff Deputy Rick Grimes leads a group of survivors in a world overrun by the walking dead. Fighting the dead as well as the living.",
    year: 2010,
    rating: "A",
    duration: "11 Seasons",
    genres: ["Drama", "Horror", "Thriller"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 121,
    title: "You",
    img: "shows img/you.jpg",
    banner: "shows img/You.webp",
    description: "A dangerously charming, intensely obsessive young man goes to extreme measures to insert himself into the lives of those he is transfixed by.",
    year: 2018,
    rating: "A",
    duration: "4 Seasons",
    genres: ["Crime", "Drama", "Romance"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 122,
    title: "Young Sheldon",
    img: "shows img/youngsheldon.webp",
    banner: "shows img/Young Sheldon.webp",
    description: "Meet a child genius named Sheldon Cooper (already seen as an adult in The Big Bang Theory) and his family. Some unique challenges face Sheldon who is socially impaired.",
    year: 2017,
    rating: "U/A 13+",
    duration: "7 Seasons",
    genres: ["Comedy"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 123,
    title: "Naruto",
    img: "shows img/naruto.webp",
    banner: "shows img/Naruto.webp",
    description: "Naruto Uzumaki, a mischievous adolescent ninja, struggles as he searches for recognition and dreams of becoming the Hokage, the village's leader and strongest ninja.",
    year: 2002,
    rating: "U/A 13+",
    duration: "4 Seasons",
    genres: ["Anime", "Action", "Adventure"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  }
];

/**
 * CATEGORIES — Each row on the browse page.
 * `filter` picks movies by ID. Allows the same movie in multiple categories.
 */
const CATEGORIES = [
  {
    name: "Top Picks For You",
    showRank: false,
    ids: [201,72,71,121,203,93,27,97,106,21,107]
  },
  {
    name: "Award Winning TV Shows",
    showRank: false,
    ids: [83,6,113,79,17,77,104,84,115,14,86,91]
  },
  {
    name: "Action Movies",
    showRank: false,
    ids: [27,44,56,202,42,23,65,13,15,40,203,70,18]
  },
  {
    name: "Crowd Pleasers",
    showRank: false,
    ids: [74,41,43,54,83,96,115,88,20,50,9,26]
  },
  {
    name: "Top 10 Movies in India Today",
    showRank: true,
    ids: [1,202, 203, 58, 7, 54, 201, 51, 9, 4]
  },
  {
    name: "Comedies",
    showRank: false,
    ids: [47, 48, 49,13,26,28,62,68,34,59,32,67]
  },
  {
    name: "Imaginative TV Shows",
    showRank: false,
    ids: [204,96,71,115,110,72,100,118,117,120]
  },
  {
    name: "Romantic Movies",
    showRank: false,
    ids: [4,57,62,28,66,19,21,68,32,201]
  },
  {
    name: "Top 10 TV Shows in India Today",
    showRank: true,
    ids: [204,2,205,3,75,93,89,5,8,83]
  },
  {
    name: "Thrillers",
    showRank: false,
    ids: [35,52,50,55,25,9,51,67,13,41]
  },
  {
    name: "Spy and Mystery",
    showRank: false,
    ids: [36,40,1,42,13,67,70,53,47,48]
  },
  {
    name: "Adventure",
    showRank: false,
    ids: [22,24,30,69,202,53,56,55,44,28]
  },
  {
    name: "Anime",
    showRank: false,
    ids: [76,80,82,84,85,93,100,103,105,123,109]
  },
  {
    name: "Indian Drama",
    showRank: false,
    ids: [89,47,92,108,32,16,205,23,39,43,59]
  },
  {
    name: "Sci-Fi",
    showRank: false,
    ids: [24,11,33,105,71,72,38,45,22,202,5]
  },
  {
    name: "Fantasy",
    showRank: false,
    ids: [6,30,34,56,74,84,93,96,97,110,112,115,118]
  },

];

/** Helper — get movie by ID */
function getMovieById(id) {
  return MOVIES.find(m => m.id === id);
}

/** Helper — get movies for a category */
function getCategoryMovies(category) {
  return category.ids.map(getMovieById).filter(Boolean);
}

/** Helper — get a random featured movie (for billboard) */
function getRandomFeatured() {
  const featured = [1, 5, 11, 12, 15]; // curated list for hero
  const id = featured[Math.floor(Math.random() * featured.length)];
  return getMovieById(id);
}
