/* =====================================================
   DATA — Movie & Show catalogue
   6 categories, each with 10 titles.
   ===================================================== */

const MOVIES = [
    {
    id: 2,
    title: "Hello Baccho",
    img: "shows img/hello bachho.jpg",
    banner: "banners/hello bachhon.webp",
    description: "A physics teacher sets out to make quality education accessible to all students through online learning,Based on the true story.",
    year: 2025,
    rating: "U/A 13+",
    duration: "5 Episodes",
    genres: ["Sincere", "Drama","Inspiring"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4"
  },
  {
    id: 3,
    title: "Kapil Sharma Show",
    img: "shows img/kapilshow.jpg",
    banner: "banners/kapil sharma show.webp",
    description: "India's favourite comedy show where Kapil Sharma hosts Bollywood stars and delivers laugh-out-loud performances every weekend.",
    year: 2024,
    rating: "U/A 13+",
    duration: "4 Seasons",
    genres: ["Comedy", "Talk Show","celebrities"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4"
  },
  {
    id: 5,
    title: "Stranger Things",
    img: "shows img/strangerthings.jpg",
    banner: "banners/ST.webp",
    description: "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl.",
    year: 2022,
    rating: "U/A 16+",
    duration: "5 Seasons",
    genres: ["Sci-Fi", "Horror", "Drama"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4"
  },
  {
    id: 6,
    title: "Wednesday",
    img: "shows img/wednesday.jpg",
    banner: "Images/trending image/Wednesday img.jpg",
    description: "Wednesday Addams is sent to Nevermore Academy, where she attempts to master her psychic ability and solve a mystery connected to her family.",
    year: 2022,
    rating: "U/A 13+",
    duration: "2 Season",
    genres: ["Comedy", "Mystery", "Fantasy"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4"
  },
  {
    id: 8,
    title: "Mandala Murders",
    img: "shows img/mandala murders.jpg",
    banner: "banners/mandala murders.webp",
    description: "Two investigators embark on a mission to uncover the enigma behind a series of murders, unveiling sinister secrets rooted in history.",
    year: 2024,
    rating: "A",
    duration: "1 Season",
    genres: ["Crime", "Mystery", "Thriller"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4"
  },
  {
    id: 10,
    title: "Bridgerton",
    img: "shows img/Bridgerton.jpg",
    banner: "Images/trending image/bridgeton img.jpg",
    description: "Set in the glamorous Regency era, the Bridgerton family navigates London's high society in search of love, intrigue, and scandal.",
    year: 2023,
    rating: "U/A 16+",
    duration: "4 Seasons",
    genres: ["Romance", "Drama", "Period"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4"
  },
  {
    id: 204,
    title: "One Piece",
    img: "shows img/one piece.avif",
    banner: "banners/one piece.webp",
    description: "Monkey D. Luffy and his pirate crew explore a fantastical world of endless oceans and exotic islands in search of the world's ultimate treasure to become the next Pirate King.",
    year: 2023,
    rating: "U/A 16+",
    duration: "2 Seasons",
    genres: ["Imaginative", "Adventure", "Rousing"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
  },
  {
    id: 205,
    title: "Taskaree: The Smuggler's Web",
    img: "shows img/taskaree.webp",
    banner: "banners/taskaree banner.webp",
    description: "A dedicated customs officer and his team take on a notorious smuggler leading a powerful syndicate, but unexpected obstacles threaten their mission.",
    year: 2026,
    rating: "U/A 16+",
    duration: "7 Episodes",
    genres: ["Crime", "Witty", "Thriller"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
  },
    {
    id: 11,
    title: "Dark",
    img: "shows img/dark2.jpg",
    banner: "banners/dark.webp",
    description: "When two children go missing in a small German town, its sinful past is exposed along with the double lives and fractured relationships that exist among four families as they search for the kids",
    year: 2017,
    rating: "U/A 16+",
    duration: "3 Seasons",
    genres: ["Sci-Fi", "Mystery", "Mind-Bending"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
  },
  {
    id: 12,
    title: "Money Heist",
    img: "shows img/money heist.jpg",
    banner: "banners/moneyhiest.webp",
    description: "A criminal mastermind who goes by 'The Professor' recruits eight people to carry out an elaborate heist on the Royal Mint of Spain.",
    year: 2021,
    rating: "U/A 16+",
    duration: "5 Seasons",
    genres: ["Suspenseful", "Exciting", "Thriller"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4"
  },
  {
    id: 13,
    title: "Red Notice",
    img: "movies img/red notice.jpg",
    banner: "Images/popular image/red-notice.jpg",
    description: "An FBI agent teams up with a notorious art thief to catch an even more notorious criminal in a globe-trotting adventure.",
    year: 2021,
    rating: "U/A 13+",
    duration: "1h 58m",
    genres: ["Action", "Comedy", "Thriller"],
    type: "Movie",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4"
  },
  {
    id: 14,
    title: "Dahmer",
    img: "shows img/dahmer.webp",
    banner: "Images/popular image/Dahmar img.webp",
    description: "The chilling true story of one of America's most notorious serial killers, as told through the eyes of his victims.",
    year: 2022,
    rating: "A",
    duration: "10 Episodes",
    genres: ["Crime", "Drama", "Biography"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4"
  },
  {
    id: 15,
    title: "Extraction",
    img: "movies img/extaction.jpg",
    banner: "banners/extraction.webp",
    description: "A hardened mercenary's mission becomes a soul-searching race to survive when he's sent to rescue a crime lord's kidnapped son.",
    year: 2020,
    rating: "U/A 16+",
    duration: "1h 58m",
    genres: ["Action", "Thriller"],
    type: "Movie",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4"
  },
  {
    id: 16,
    title: "Sacred Games",
    img: "shows img/sacredgames.jpg",
    banner: "Images/popular image/Sacred games img.webp",
    description: "A link in a chain of events leads a troubled cop to the doorstep of a powerful crime lord, uncovering a conspiracy that threatens Mumbai.",
    year: 2019,
    rating: "A",
    duration: "2 Seasons",
    genres: ["Crime", "Thriller", "Drama"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4"
  },
  {
    id: 17,
    title: "Adolescence",
    img: "shows img/adolescence.jpg",
    banner: "Images/popular image/adolescence img.jpg",
    description: "A coming-of-age drama exploring the lives of teenagers navigating love, identity, and the pressures of growing up in a connected world.",
    year: 2025,
    rating: "U/A 16+",
    duration: "4 Episodes",
    genres: ["Drama", "Coming-of-Age", "Crime"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 71,
    title: "3 Body Problem",
    img: "shows img/3 bodu problem.jpg",
    banner: "Images/popular image/adolescence img.jpg",
    description: "Across continents and decades, five brilliant friends make earth-shattering discoveries as the laws of science unravel and an existential threat emerges.",
    year: 2024,
    rating: "A",
    duration: "8 Episodes",
    genres: ["Sci-Fi", "Mystery", "Adventure"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 72,
    title: "Alice in borderland",
    img: "shows img/alice in borderland.jpg",
    banner: "Images/popular image/adolescence img.jpg",
    description: "An obsessed gamer and his friends find themselves in a deserted Tokyo where they must compete in dangerous games to survive.",
    year: 2020,
    rating: "A",
    duration: "2 Seasons",
    genres: ["Sci-Fi", "Thriller", "Action"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 73,
    title: "All of Us Are Dead",
    img: "shows img/allofusaredead.jpg",
    banner: "Images/popular image/adolescence img.jpg",
    description: "A high school becomes ground zero for a zombie virus outbreak. Trapped students must fight their way out or turn into one of the rabid infected.",
    year: 2022,
    rating: "A",
    duration: "12 Episodes",
    genres: ["Horror", "Action", "Drama"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 74,
    title: "Avtar: The Last Airbender",
    img: "shows img/avtar.jpg",
    banner: "Images/popular image/adolescence img.jpg",
    description: "A young boy known as the Avatar must master the four elemental powers to save a world at war and fight a ruthless enemy.",
    year: 2024,
    rating: "U/A 13+",
    duration: "8 Episodes",
    genres: ["Fantasy", "Adventure", "Action"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 75,
    title: "Bads of Bollywood",
    img: "shows img/badsofbollywood.jpg",
    banner: "banners/bads of Bollywood.webp",
    description: "A deep dive into the evolution of the 'villain' in Indian cinema, exploring the iconic actors who defined evil on screen.",
    year: 2024,
    rating: "U/A 13+",
    duration: "1 Season",
    genres: ["Comedy", "Chilling","Bollywood"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 76,
    title: "Bakitu",
    img: "shows img/bakitu.jpg",
    banner: "Images/popular image/adolescence img.jpg",
    description: "Five years after the Great Raitai Tournament, Baki Hanma trains intensely to challenge his father, Yuujirou Hanma.",
    year: 2023,
    rating: "A",
    duration: "2 Seasons",
    genres: ["Anime", "Action", "Martial Arts"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 77,
    title: "Better Call Saul",
    img: "shows img/bettercallsaul.webp",
    banner: "Images/popular image/adolescence img.jpg",
    description: "The trials and tribulations of criminal lawyer Jimmy McGill in the years leading up to his fateful run-in with Walter White.",
    year: 2015,
    rating: "A",
    duration: "6 Seasons",
    genres: ["Crime", "Drama"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 78,
    title: "Bodyguard",
    img: "shows img/bodyguard.jpg",
    banner: "Images/popular image/adolescence img.jpg",
    description: "A war veteran is assigned to protect a politician whose politics he despises, leading to a web of conspiracy and danger.",
    year: 2018,
    rating: "A",
    duration: "6 Episodes",
    genres: ["Thriller", "Crime", "Drama"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 79,
    title: "Breaking Bad",
    img: "shows img/breaking bad.webp",
    banner: "Images/popular image/adolescence img.jpg",
    description: "A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine.",
    year: 2008,
    rating: "A",
    duration: "5 Seasons",
    genres: ["Crime", "Drama", "Thriller"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 80,
    title: "Chainsaw Man",
    img: "shows img/chainsaw man.webp",
    banner: "Images/popular image/adolescence img.jpg",
    description: "Denji, a teenager living in poverty, is reborn as a powerful Devil Hunter with chainsaw limbs after merging with his pet devil.",
    year: 2022,
    rating: "A",
    duration: "12 Episodes",
    genres: ["Anime", "Action", "Horror"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 81,
    title: "Cobra Kai",
    img: "shows img/cobra kai.jpg",
    banner: "Images/popular image/adolescence img.jpg",
    description: "Decades after their 1984 All Valley Karate Tournament bout, a middle-aged Daniel LaRusso and Johnny Lawrence find themselves martial-arts rivals again.",
    year: 2018,
    rating: "U/A 16+",
    duration: "6 Seasons",
    genres: ["Action", "Comedy", "Drama"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 82,
    title: "Death Note",
    img: "shows img/deathnote.webp",
    banner: "Images/popular image/adolescence img.jpg",
    description: "An intelligent high school student goes on a secret crusade to eliminate criminals from the world after discovering a notebook that can kill anyone.",
    year: 2006,
    rating: "U/A 16+",
    duration: "37 Episodes",
    genres: ["Anime", "Mystery", "Thriller"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 83,
    title: "Delhi Crime",
    img: "shows img/delhicrime.jpg",
    banner: "banners/delhi crime.webp",
    description: "Based on real-life case files, this anthology series follows the Delhi Police as they investigate high-profile crimes.",
    year: 2019,
    rating: "A",
    duration: "3 Seasons",
    genres: ["Crime", "Drama"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 84,
    title: "Demon Slayer",
    img: "shows img/demon slayer.webp",
    banner: "Images/popular image/adolescence img.jpg",
    description: "A family is attacked by demons and only two members survive - Tanjiro and his sister Nezuko, who is turning into a demon slowly.",
    year: 2019,
    rating: "U/A 16+",
    duration: "4 Seasons",
    genres: ["Anime", "Action", "Fantasy"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 85,
    title: "Dragon Ball Z",
    img: "shows img/dragonball Z.webp",
    banner: "Images/popular image/adolescence img.jpg",
    description: "Goku and his companions defend the Earth against an assortment of villains ranging from intergalactic space fighters to powerful androids.",
    year: 1989,
    rating: "U/A 13+",
    duration: "9 Seasons",
    genres: ["Anime", "Action", "Adventure"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 86,
    title: "Elite",
    img: "shows img/elite.jpg",
    banner: "Images/popular image/adolescence img.jpg",
    description: "When three working-class teenagers begin attending an exclusive private school in Spain, the clash between them and the wealthy students leads to murder.",
    year: 2018,
    rating: "A",
    duration: "8 Seasons",
    genres: ["Crime", "Drama", "Thriller"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 87,
    title: "Emily in Paris",
    img: "shows img/emily in paris.jpg",
    banner: "Images/popular image/adolescence img.jpg",
    description: "A young American woman from the Midwest is hired by a marketing firm in Paris to provide them with an American perspective on things.",
    year: 2020,
    rating: "U/A 16+",
    duration: "4 Seasons",
    genres: ["Comedy", "Romance", "Drama"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 88,
    title: "Good Doctor",
    img: "shows img/good doctor.webp",
    banner: "Images/popular image/adolescence img.jpg",
    description: "Shaun Murphy, a young surgeon with autism and Savant syndrome, is recruited into the surgical unit of a prestigious hospital.",
    year: 2017,
    rating: "U/A 16+",
    duration: "7 Seasons",
    genres: ["Drama"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 89,
    title: "Heeramandi",
    img: "shows img/heeramandi.jpg",
    banner: "banners/heeramandi.webp",
    description: "In pre-independent India, the lives of courtesans in the red-light district of Heera Mandi are filled with love, betrayal, and politics.",
    year: 2024,
    rating: "U/A 16+",
    duration: "8 Episodes",
    genres: ["Drama", "History", "Romance"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 90,
    title: "Hellbound",
    img: "shows img/hellbound.jpg",
    banner: "show img/hellbound.webp",
    description: "Unearthly beings deliver bloody condemnations, sending individuals to hell and giving rise to a religious group founded on the idea of divine justice.",
    year: 2021,
    rating: "A",
    duration: "2 Seasons",
    genres: ["Horror", "Mystery", "Crime"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 91,
    title: "House of cards",
    img: "shows img/house of cards.jpg",
    banner: "shows img/house of cards.jpg",
    description: "A Congressman works with his equally conniving wife to exact revenge on the people who betrayed him.",
    year: 2013,
    rating: "A",
    duration: "6 Seasons",
    genres: ["Drama"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 92,
    title: "Jamtara",
    img: "shows img/jamtara.jpg",
    banner: "Images/popular image/adolescence img.jpg",
    description: "A group of small-town young men run a lucrative phishing operation until a corrupt politician wants in on their scheme.",
    year: 2020,
    rating: "A",
    duration: "2 Seasons",
    genres: ["Crime", "Drama"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 93,
    title: "Jijutsu Kaisen",
    img: "shows img/jijutsu.webp",
    banner: "banners/jijutsu kaisen.webp",
    description: "A boy swallows a cursed talisman and becomes cursed himself. He enters a shaman's school to be able to locate the demon's other body parts and thus exorcise himself.",
    year: 2020,
    rating: "A",
    duration: "2 Seasons",
    genres: ["Anime", "Action", "Fantasy"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 94,
    title: "Kota Factory",
    img: "shows img/kota factory.jpg",
    banner: "Images/popular image/adolescence img.jpg",
    description: "Dedicated to the students of Kota, the show captures the life of IIT-JEE aspirants and their struggle to clear the entrance exams.",
    year: 2019,
    rating: "U/A 16+",
    duration: "3 Seasons",
    genres: ["Comedy", "Drama"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 95,
    title: "Kurukshetra",
    img: "shows img/krukshetra.jpg",
    banner: "Images/popular image/adolescence img.jpg",
    description: "A modern retelling of the epic battle of Mahabharata, exploring the themes of duty, family, and power.",
    year: 2024,
    rating: "U/A 13+",
    duration: "10 Episodes",
    genres: ["Drama", "Action", "Mythology"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 96,
    title: "Locke & Key",
    img: "shows img/locke and key.jpg",
    banner: "shows img/locke & key.webp",
    description: "After their father is murdered, three siblings move into a house filled with reality-bending keys.",
    year: 2020,
    rating: "U/A 13+",
    duration: "3 Seasons",
    genres: ["Fantasy", "Horror", "Mystery"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 97,
    title: "Lucifer",
    img: "shows img/lucifer.jpg",
    banner: "shows img/lucifer.webp",
    description: "Lucifer Morningstar has decided he's had enough of being the dutiful servant in Hell and decides to spend some time on Earth to better understand humanity.",
    year: 2016,
    rating: "A",
    duration: "6 Seasons",
    genres: ["Crime", "Fantasy", "Drama"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 98,
    title: "Mandala Murders",
    img: "shows img/Mandala murders.jpg",
    banner: "Images/popular image/adolescence img.jpg",
    description: "Detectives race against time to solve a series of grisly murders linked by a mysterious religious symbol.",
    year: 2024,
    rating: "A",
    duration: "8 Episodes",
    genres: ["Crime", "Thriller", "Mystery"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 99,
    title: "Money Heist",
    img: "shows img/money heist.jpg",
    banner: "shows img/money heist.jpg",
    description: "An unusual group of robbers attempt to carry out the most perfect robbery in Spanish history - stealing 2.4 billion Euros from the Royal Mint of Spain.",
    year: 2017,
    rating: "A",
    duration: "5 Seasons",
    genres: ["Action", "Crime", "Drama"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 100,
    title: "My Hero Academia",
    img: "shows img/my hero academy.webp",
    banner: "shows img/my hero academia.webp",
    description: "A superhero-loving boy without any powers is determined to enroll in a prestigious hero academy and learn what it really means to be a hero.",
    year: 2016,
    rating: "U/A 13+",
    duration: "7 Seasons",
    genres: ["Anime", "Action", "Adventure"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 101,
    title: "Narcos",
    img: "shows img/narcos.jpg",
    banner: "shows img/narcos.webp",
    description: "A chronicled look at the criminal exploits of Colombian drug lord Pablo Escobar, as well as many other drug kingpins who plagued the country through the years.",
    year: 2015,
    rating: "A",
    duration: "3 Seasons",
    genres: ["Biography", "Crime", "Drama"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 102,
    title: "One Punch Man",
    img: "shows img/one punch man.webp",
    banner: "shows img/one punch man.webp",
    description: "The story of Saitama, a hero who can defeat any enemy with a single punch, but suffers from boredom due to his overwhelming strength.",
    year: 2015,
    rating: "U/A 16+",
    duration: "2 Seasons",
    genres: ["Anime", "Action", "Comedy"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 103,
    title: "One piece",
    img: "shows img/one-piece anime.webp",
    banner: "Images/popular image/adolescence img.jpg",
    description: "Monkey D. Luffy and his pirate crew explore a fantastical world of endless oceans and exotic islands in search of the world's ultimate treasure.",
    year: 1999,
    rating: "U/A 13+",
    duration: "21 Seasons",
    genres: ["Anime", "Action", "Adventure"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 104,
    title: "Ozark",
    img: "shows img/ozark.jpg",
    banner: "shows img/ozark.webp",
    description: "A financial advisor drags his family from Chicago to the Missouri Ozarks, where he must launder money to appease a drug boss.",
    year: 2017,
    rating: "A",
    duration: "4 Seasons",
    genres: ["Crime", "Drama", "Thriller"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 105,
    title: "Parayte",
    img: "shows img/parasyte.webp",
    banner: "shows img/Parayte.webp",
    description: "A teenager's hand is taken over by a parasite, and they must work together to survive and stop others of its kind from consuming humanity.",
    year: 2014,
    rating: "A",
    duration: "24 Episodes",
    genres: ["Anime", "Action", "Sci-Fi"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 106,
    title: "Peaky Blinder",
    img: "shows img/peaky blinders.jpg",
    banner: "shows img/Peaky Blinder.webp",
    description: "A gangster family epic set in 1900s England, centering on a gang who sew razor blades in the peaks of their caps.",
    year: 2013,
    rating: "A",
    duration: "6 Seasons",
    genres: ["Crime", "Drama"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 107,
    title: "Queens Gambit",
    img: "shows img/queensgambit.jpg",
    banner: "shows img/Queens Gambit.webp",
    description: "Orphaned at nine, prodigious introvert Beth Harmon discovers and masters the game of chess in 1960s USA.",
    year: 2020,
    rating: "U/A 16+",
    duration: "7 Episodes",
    genres: ["Drama"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 108,
    title: "Rana Naidu",
    img: "shows img/raina naidu.jpg",
    banner: "Images/popular image/adolescence img.jpg",
    description: "Rana Naidu is the go-to fixer for Bollywood's elite, but his life is thrown into chaos when his father is released from prison.",
    year: 2023,
    rating: "A",
    duration: "1 Season",
    genres: ["Action", "Crime", "Drama"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 109,
    title: "Sakamoto Days",
    img: "shows img/sakamoto.jpg",
    banner: "shows img/sakamoto days.webp",
    description: "Taro Sakamoto, an unbeatable legendary assassin, retires and settles down to run a neighborhood grocery store, but his past soon catches up.",
    year: 2025,
    rating: "A",
    duration: "12 Episodes",
    genres: ["Anime", "Action", "Comedy"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 110,
    title: "Sandman",
    img: "shows img/sandman.jpg",
    banner: "shows img/sandman.webp",
    description: "Upon escaping after decades of imprisonment by a mortal wizard, Dream, the personification of dreams, sets out to reclaim his lost equipment.",
    year: 2022,
    rating: "A",
    duration: "1 Season",
    genres: ["Fantasy", "Drama", "Mystery"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 111,
    title: "Sex Education",
    img: "shows img/sexeducation.jpg",
    banner: "shows img/sex education.webp",
    description: "A teenage boy with a sex therapist mother teams up with a high school classmate to set up an underground sex therapy clinic at school.",
    year: 2019,
    rating: "A",
    duration: "4 Seasons",
    genres: ["Comedy", "Drama"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 112,
    title: "Shadow and Bone",
    img: "shows img/shadow and bones.jpg",
    banner: "Images/popular image/adolescence img.jpg",
    description: "Sinister forces plot against a young soldier when she reveals a magical power that might unite her world.",
    year: 2021,
    rating: "U/A 16+",
    duration: "2 Seasons",
    genres: ["Fantasy", "Action", "Drama"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 113,
    title: "Squid Game",
    img: "shows img/squid games.jpg",
    banner: "shows img/squid game.webp",
    description: "Hundreds of cash-strapped players accept a strange invitation to compete in children's games. Inside, a tempting prize awaits with deadly high stakes.",
    year: 2021,
    rating: "A",
    duration: "2 Seasons",
    genres: ["Thriller", "Action", "Drama"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 114,
    title: "Suits",
    img: "shows img/suits.webp",
    banner: "shows img/suits.webp",
    description: "On the run from a drug deal gone bad, brilliant college dropout Mike Ross finds himself working with Harvey Specter, one of NYC's best lawyers.",
    year: 2011,
    rating: "U/A 16+",
    duration: "9 Seasons",
    genres: ["Comedy", "Drama"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 115,
    title: "The Witcher",
    img: "shows img/thewitcher.jpg",
    banner: "shows img/the witcher.webp",
    description: "Geralt of Rivia, a solitary monster hunter, struggles to find his place in a world where people often prove more wicked than beasts.",
    year: 2019,
    rating: "A",
    duration: "3 Seasons",
    genres: ["Fantasy", "Action", "Adventure"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 116,
    title: "Titans",
    img: "shows img/titans.jpg",
    banner: "shows img/Titans.webp",
    description: "A team of young superheroes led by Nightwing combat evil and other perils in this gritty take on the DC franchise.",
    year: 2018,
    rating: "A",
    duration: "4 Seasons",
    genres: ["Action", "Adventure", "Crime"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 117,
    title: "Umbrella Academy",
    img: "shows img/umbrella academy.jpg",
    banner: "shows img/umbrella academy.webp",
    description: "A family of former child heroes, now grown apart, must reunite to continue to protect the world.",
    year: 2019,
    rating: "U/A 16+",
    duration: "4 Seasons",
    genres: ["Action", "Adventure", "Comedy"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 118,
    title: "Vampire Diaries",
    img: "shows img/vampiredairy.webp",
    banner: "shows img/vampire diaries.webp",
    description: "The lives, loves, dangers and disasters in the town, Mystic Falls, Virginia. Creatures of unspeakable horror lurk beneath this town as a teenage girl is suddenly torn between two vampire brothers.",
    year: 2009,
    rating: "U/A 16+",
    duration: "8 Seasons",
    genres: ["Drama", "Fantasy", "Horror"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 119,
    title: "Vikings",
    img: "shows img/vikings.webp",
    banner: "shows img/Vikings.webp",
    description: "Vikings transports us to the brutal and mysterious world of Ragnar Lothbrok, a Viking warrior and farmer who yearns to explore—and raid—the distant shores across the ocean.",
    year: 2013,
    rating: "A",
    duration: "6 Seasons",
    genres: ["Action", "Adventure", "Drama"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 120,
    title: "Walking Dead",
    img: "shows img/walkingdead.webp",
    banner: "shows img/Walking Dead.webp",
    description: "Sheriff Deputy Rick Grimes leads a group of survivors in a world overrun by the walking dead. Fighting the dead as well as the living.",
    year: 2010,
    rating: "A",
    duration: "11 Seasons",
    genres: ["Drama", "Horror", "Thriller"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 121,
    title: "You",
    img: "shows img/you.jpg",
    banner: "shows img/You.webp",
    description: "A dangerously charming, intensely obsessive young man goes to extreme measures to insert himself into the lives of those he is transfixed by.",
    year: 2018,
    rating: "A",
    duration: "4 Seasons",
    genres: ["Crime", "Drama", "Romance"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 122,
    title: "Young Sheldon",
    img: "shows img/youngsheldon.webp",
    banner: "shows img/Young Sheldon.webp",
    description: "Meet a child genius named Sheldon Cooper (already seen as an adult in The Big Bang Theory) and his family. Some unique challenges face Sheldon who is socially impaired.",
    year: 2017,
    rating: "U/A 13+",
    duration: "7 Seasons",
    genres: ["Comedy"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  },
  {
    id: 123,
    title: "Naruto",
    img: "shows img/naruto.webp",
    banner: "shows img/Naruto.webp",
    description: "Naruto Uzumaki, a mischievous adolescent ninja, struggles as he searches for recognition and dreams of becoming the Hokage, the village's leader and strongest ninja.",
    year: 2002,
    rating: "U/A 13+",
    duration: "4 Seasons",
    genres: ["Anime", "Action", "Adventure"],
    type: "TV Show",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"
  }
];

/**
 * CATEGORIES — Each row on the browse page.
 * `filter` picks movies by ID. Allows the same movie in multiple categories.
 */
const CATEGORIES = [
 {
    name: "Award Winning TV Shows",
    showRank: false,
    ids: [83,6,113,79,17,77,104,84,115,14,86,91]
  },
  {
    name: "Top 10 TV Shows in India Today",
    showRank: true,
    ids: [204,2,205,3,75,93,89,5,8,83]
  },
  {
    name: "Imaginative TV Shows",
    showRank: false,
    ids: [204,96,71,115,110,72,100,118,117,120]
  },
  {
    name: "Anime",
    showRank: false,
    ids: [76,80,82,84,85,93,100,103,105,123,109]
  },
  {
    name: "US TV Shows",
    showRank: false,
    ids: [79,77,81,87,71,88,91,10,86,104,5,114]
  },
  {
    name: "Made in India",
    showRank: false,
    ids: [75,83,89,2,3,94,95,8,108,16,205]
  },
  {
    name: "Crime TV Shows",
    showRank: false,
    ids: [83,12,97,11,79,106,8,77,17,205,92,101]
  },

];

/** Helper — get movie by ID */
function getMovieById(id) {
  return MOVIES.find(m => m.id === id);
}

/** Helper — get movies for a category */
function getCategoryMovies(category) {
  return category.ids.map(getMovieById).filter(Boolean);
}

/** Helper — get a random featured movie (for billboard) */
function getRandomFeatured() {
  const featured = [1, 5, 11, 12, 15]; // curated list for hero
  const id = featured[Math.floor(Math.random() * featured.length)];
  return getMovieById(id);
}
